services:
  db:
    image: postgres:15
    container_name: ddaw_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddaw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ddaw"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: ddaw_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy